### ISSUE TITLE
Trouble with loading old palettes 

### ISSUE THREAD

**Issue by stelskii** [Krazete/sgmpalette#1]
I can't seem to load my old pallete pngs correctly. While all the colour codes are on the character, they're not in the same places they used to be. If you cannot change the what numbers are assigned to the colour map, would I be able to use an old ver of the site? Thank you.

**Comment by Krazete** [comment]
Yeah, sorry; SGM changed all color codes in version 5.2.0.
I didn't think they'd ever do that when I implemented the palette save/load function.

If you need the old version, you can fork this repo and deploy GitHub Pages from the `pre5.2.0` branch.
(I'd do it, but I can't fork my own repo.)

Looks like you're new here, so here are some instructions:
1. Click Fork on the top right.
2. Deselect the "Copy the `master` branch only" option. Create fork.
3. On your forked repo, click Settings. In the sidebar under Code and Automation, click Pages.
4. Select Source > Deploy from a Branch. For the branch, select `pre5.2.0` `/ (root)`. Save.
5. Wait a few minutes. Refresh the page until it says your site is live.
